name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.fish"
  pull_request:
    branches:
      - main
    paths:
      - "**.fish"

defaults:
  run:
    shell: dash {0}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Install fish
        uses: fish-actions/install-fish@v1.1.0

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Lint fish scripts
        run: fish lint.fish

      - name: Lint consistency
        run: fish lint-consistency.fish
